module.exports = [
    "AirBnB", 
    "Uber", 
    "Udemy", 
    "Tinder", 
    "9GAG", 
    "SpaceX", 
    "Stripe",
    "WeWork",
    "Lyft",
    "JUUL Labs",
    "Pinterest",
    "Hulu",
    "Slack",
    "Magic Leap",
    "Robinhood",
    "Zenefits",
    "Peloton",
    "Credit Karma",
    "Oscar Health",
    "SmileDirectClub",
    "Fanatics",
    "SoFi",
    "Vice Media",
    "Qaultrics",
    "Mozido",
    "Compass",
    "Domo",
    "GitHub",
    "Instacart",
    "SurveyMonkey",
    "Reddit",
    "Quora",
    "Sprinklr",
    "Tanium",
    "Squarespace",
    "The Honest Company",
    "Coinbase",
    "Afiniti",
    "HeartFlow",
    "Razer Inc.",
    "Snowflake Computing",
    "C3 IoT",
    "DoorDash",
    "Toast",
    "Thumbtack",
    "Rubrik",
    "PagerDuty",
    "Warby Parker",
    "Postmates",
    "GitLab",
    "LimeBike",
    "UiPath Inc.",
    "Convoy",
    "JFrog",
    "CrowdStrike",
    "Vox Media",
    "InVision",
    "Lookout Security",
    "Udacity",
    "MedMen",
    "ThoughSpot",
    "Talkdesk"
];
