module.exports = [
    "AirBnB", 
    "Uber", 
    "Udemy", 
    "Tinder", 
    "9GAG", 
    "SpaceX", 
    "Stripe",
    "WeWork",
    "Lyft",
    "JUUL Labs",
    "Pinterest",
    "Hulu",
    "Slack",
    "Magic Leap",
    "Robinhood",
    "Zenefits",
    "Peloton",
    "Credit Karma",
    "Oscar Health",
    "SmileDirectClub",
    "Fanatics",
    "SoFi",
    "Vice Media",
    "Qaultrics",
    "Mozido",
    "Compass",
    "Domo",
    "GitHub",
    "Instacart",
    "SurveyMonkey",
    "Reddit",
    "Quora",
    "Sprinklr",
    "Tanium",
    "Squarespace",
    "The Honest Company",
    "Coinbase",
    "Afiniti",
    "HeartFlow",
    "Razer Inc.",
    "Snowflake Computing",
    "C3 IoT",
    "DoorDash",
    "Toast",
    "Thumbtack",
    "Rubrik",
    "PagerDuty",
    "Warby Parker",
    "Postmates",
    "GitLab",
    "LimeBike",
    "UiPath Inc.",
    "Convoy",
    "JFrog",
    "CrowdStrike",
    "Vox Media",
    "InVision",
    "Lookout Security",
    "Udacity",
    "MedMen",
    "ThoughSpot",
    "Talkdesk",
    "Amazon",
    "Google",
    "Facebook",
    "Apple",
    "Tesla Motors",
    "eBay",
    "Craigslist",
    "Letgo",
    "Meetup",
    "LinkedIn",
    "Netflix",
    "Spotify",
    "Square",
    "Waze",
    "Patreon",
    "YouTube",
    "Twitch",
    "Pinterest",
    "Upwork",
    "Fiverr",
    "Walmart",
    "Twitter",
    "Microsoft",
    "Zynga",
    "Groupon",
    "Foursquare",
    "Raspberry Pi Foundation",
    "GoFundMe",
    "SolarCity",
    "Pandora",
    "Dropbox",
    "LegalZoom",
    "Starbucks",
    "Gogo",
    "Kickstarter",
    "SoundCloud",
    "PayPal",
    "Y Combinator",
    "Splunk",
    "Sproxil",
    "SodaStream",
    "Yelp",
    "BitTorrent",
    "Tor Project",
    "Usenet",
    "Nest",
    "Evernote",
    "Roku",
    "SeeGrid",
    "AngelList",
    "Angie's List",
    "Tumblr",
    "Shazam",
    "Fitbit",
    "GoPro",
    "Flipboard",
    "Alibaba",
    "Instagram",
    "Ikea",
    "BuzzFeed",
    "Hudl",
    "Box",
    "Shopify",
    "Houzz",
    "Snap",
    "Twilio",
    "Chobani",
    "Xiaomi",
    "TaskRabbit",
    "Headspace",
    "Napster",
];
